# Generated by Django 4.1.2 on 2022-12-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wings',
            name='date',
        ),
    ]
