# Generated by Django 4.1.2 on 2022-12-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_wings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wings',
            name='add',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wings',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='wings',
            name='point',
            field=models.CharField(max_length=1000),
        ),
    ]
