# Generated by Django 4.1.2 on 2022-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_wings_add_alter_wings_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wings',
            name='add',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wings',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wings',
            name='point',
            field=models.TextField(),
        ),
    ]
