# Generated by Django 4.1.2 on 2022-12-26 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_wings_add_alter_wings_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wings',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 16, 4, 10, 842001)),
        ),
    ]
