# Generated by Django 4.1.2 on 2022-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_wings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wings',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
