# Generated by Django 4.1.2 on 2022-12-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_wings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wings',
            name='date',
        ),
    ]
